# Generated by Django 2.2 on 2020-06-12 08:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fixedItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='seasonalItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=50)),
                ('season', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='seasons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=50)),
                ('temperatureStart', models.CharField(max_length=10)),
                ('temperatureEnd', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='WH',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('text', models.CharField(max_length=50)),
                ('temperature', models.CharField(max_length=10)),
                ('descrip', models.CharField(max_length=10)),
                ('icon', models.CharField(max_length=10)),
            ],
        ),
    ]
