# Generated by Django 2.2 on 2020-06-12 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_fixeditems_seasonalitems'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seasons',
            name='temperatureEnd',
        ),
        migrations.RemoveField(
            model_name='seasons',
            name='temperatureStart',
        ),
    ]
