# Generated by Django 2.2 on 2020-06-12 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0004_auto_20200612_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='seasons',
            name='temperatureEnd',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='seasons',
            name='temperatureStart',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
